// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// jsonAdaptors is an autogenerated mock type for the jsonAdaptors type
type jsonAdaptors struct {
	mock.Mock
}

type mockConstructorTestingTnewJsonAdaptors interface {
	mock.TestingT
	Cleanup(func())
}

// newJsonAdaptors creates a new instance of jsonAdaptors. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newJsonAdaptors(t mockConstructorTestingTnewJsonAdaptors) *jsonAdaptors {
	mock := &jsonAdaptors{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
