// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VwapCalculationEngine is an autogenerated mock type for the VwapCalculationEngine type
type VwapCalculationEngine struct {
	mock.Mock
}

// Calculate provides a mock function with given fields: price, volume
func (_m *VwapCalculationEngine) Calculate(price float64, volume float64) float64 {
	ret := _m.Called(price, volume)

	var r0 float64
	if rf, ok := ret.Get(0).(func(float64, float64) float64); ok {
		r0 = rf(price, volume)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

type mockConstructorTestingTNewVwapCalculationEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewVwapCalculationEngine creates a new instance of VwapCalculationEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVwapCalculationEngine(t mockConstructorTestingTNewVwapCalculationEngine) *VwapCalculationEngine {
	mock := &VwapCalculationEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
